# Generated by Django 3.1.5 on 2023-08-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
