# Generated by Django 3.1.5 on 2023-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0002_remove_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
