# Generated by Django 3.1.5 on 2023-08-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0005_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='dayweek',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='speciality',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
